// File: cpautre variable labels.do

// Apply capture labels to variables
capture label variable fsu_serial_no "FSU Serial Number"
capture label variable schedule "Schedule"
capture label variable sector "Sector"
capture label variable nss_region "NSS Region"
capture label variable district "District"
capture label variable stratum "Stratum"
capture label variable sub_stratum "Sub-stratum"
capture label variable sub_round "Sub-round"
capture label variable fod_sub_region "FOD Sub-region"
capture label variable segment_no "Segment Number"
capture label variable sec_stage_stratum_no "Second Stage Stratum Number"
capture label variable sample_est_no "Sample Establishment Number"
capture label variable level "Level"
capture label variable survey_code "Survey Code"
capture label variable status_code "Status Code"
capture label variable reason_not_surveyed "Reason for original sample not surveyed"
capture label variable response_code "Response Code"
capture label variable informant_code "Informant Code"
capture label variable date_of_survey "Date of Survey"
capture label variable time_taken "Total time taken in minutes"
capture label variable multiplier "Multiplier"

capture label variable pursuing_mixed_act "Pursuing Mixed Activities"
capture label variable major_act_nic_2008_2digit "Major Activity NIC 2008 (2-digit)"
capture label variable major_act_nic_2008_5digit "Major Activity NIC 2008 (5-digit)"
capture label variable minor_act_nic_2008_2digit "Minor Activity NIC 2008 (2-digit)"
capture label variable minor_act_nic_2008_5digit "Minor Activity NIC 2008 (5-digit)"
capture label variable type_of_ownership "Type of Ownership"
capture label variable edu_level_prop_major_partner "Edu Level Proprietor/Major Partner"
capture label variable comp_course_prop_major_part "Completed tech courses Proprietor/Major Partner"
capture label variable social_group_owner_major_par "Social Group Owner/Major Partner"
capture label variable num_economic_active_entrep "No of Economic Activities taken by Entrepreneurs"
capture label variable non_profit_institution "Is a Non-Profit Institution"
capture label variable npish_serving_households "Is NPISH (Serving Households)"
capture label variable est_has_bank_account "Establishment Has Bank Account"
capture label variable location_of_est "Location of Establishment"
capture label variable est_type "Establishment Type"
capture label variable years_of_oper_est "Years of Operation"
capture label variable year_initial_oper_current_o "Year Initial Operation  Current Owner"
capture label variable nature_of_oper "Nature of Operation"
capture label variable months_operated_ "Months Operated during last year"
capture label variable hours_worked_per_day "Hours Worked per Day"
capture label variable accounts_maintained "Accounts Maintained"
capture label variable accounts_data_in_books "Accounts Data in Books"
capture label variable accounts_period "Accounting Period"
capture label variable est_used_computer_ "Establishment Used Computer"
capture label variable est_used_internet_ "Establishment Used Internet"
capture label variable est_faced_probs_ "Establishment Faced Problems"
capture label variable severe_prob_faced_ "Most Severe Problem Faced"
capture label variable next_severe_prob_faced "Next Severe Problem Faced"
capture label variable regist_under_any_act_author "Regd Under Any Act/Authority"
capture label variable regd_under_shop_est_act "Regd Under Shops & Est Act"
capture label variable regd_under_indian_trust_act "Regd Under Indian Trust Act"
capture label variable regd_under_societies_regist "Regd Under Societies Regist Act"
capture label variable regd_under_coop_societies_a "Regd Under Coop Societies Act"
capture label variable regd_under_club_association "Regd Under Club/Association Act"
capture label variable regd_under_any_other_act "Regd Under Any Other Act"
capture label variable addn_regist_licenses_1 "Additional Regist/Licenses 1"
capture label variable addn_regist_licenses_2 "Additional Regist/Licenses 2"
capture label variable addn_regist_licenses_3 "Additional Regist/Licenses 3"
capture label variable ent_provided_manuf_services "Ent Provided Manuf Services"
capture label variable manuf_services_contract_bas "Manuf Services on Contract Basis"
capture label variable type_of_contract_manuf_serv "Type of Contract Manuf Services"
capture label variable equip_supplied_contractor "Equipment Supplied by Contractor"
capture label variable rawmaterial_supplied_contra "Raw Material Supplied Contractor"
capture label variable design_supplied_contractor "Design Supplied by Contractor"
capture label variable other_services_contract_bas "Other Services on Contract Basis"
capture label variable type_of_contract_other_serv "Type Contract for Other Services"
capture label variable franchise_outlet "Franchise Outlet"
capture label variable had_manuf "Pursued manufacturing activity"
capture label variable had_trading_activity "Pursued trading activity"
capture label variable had_transportation_act "Pursued transportation activity"
capture label variable had_warehousing_act "Pursued warehousing activity"
capture label variable had_info_communication_act "Pursued postal/courier activity"
capture label variable had_accommodation_food_act "Whether pursued accom and food service activity"
capture label variable had_financial_act "Pursued financial activity"
capture label variable had_real_estate_act "Pursued real estate activity"
capture label variable had_real_estate_act "Pursued business/professional service activity"
capture label variable had_educational_act "Pursued educational activity"
capture label variable had_health_social_veterinary_act "Pursued health/social work activity"
capture label variable had_personal_service_act "Pursued personal service activity"
capture label variable had_other_act "Pursued other activity"
capture label variable type_reference_period "Type of ref period blocks 3-9"
capture label variable days_closed_govt_order "No of days closed due to lockdown"
capture label variable selected_unit "Selected unit is a"
capture label variable total_branch_est "Total no of branch establishments"
capture label variable separate_account_for_branch_est "Separate account available select branch est"
capture label variable total_branch_est "Total no of branch establishments"

capture label variable avg_days_oper_month_1920Q1 "Avg no of days operation per month 1920Q1"
capture label variable avg_days_oper_month_1920Q2 "Avg no of days operation per month 1920Q2"
capture label variable avg_days_oper_month_1920Q3 "Avg no of days operation per month 1920Q3"
capture label variable avg_days_oper_month_1920Q4 "Avg no of days operation per month 1920Q4"
capture label variable avg_days_oper_month_2021Q1 "Avg no of days operation per month 2021Q1"
capture label variable avg_days_oper_month_2021Q2 "Avg no of days operation per month 2021Q2"
capture label variable avg_days_oper_month_2021Q3 "Avg no of days operation per month 2021Q3"
capture label variable avg_days_oper_month_2021Q4 "Avg no of days operation per month 2021Q4"

capture label variable avg_wrks_oper_month_1920Q1 "Avg no of workers operation per month 1920Q1"
capture label variable avg_wrks_oper_month_1920Q2 "Avg no of workers operation per month 1920Q2"
capture label variable avg_wrks_oper_month_1920Q3 "Avg no of workers operation per month 1920Q3"
capture label variable avg_wrks_oper_month_1920Q4 "Avg no of workers operation per month 1920Q4"
capture label variable avg_wrks_oper_month_2021Q1 "Avg no of workers operation per month 2021Q1"
capture label variable avg_wrks_oper_month_2021Q2 "Avg no of workers operation per month 2021Q2"
capture label variable avg_wrks_oper_month_2021Q3 "Avg no of workers operation per month 2021Q3"
capture label variable avg_wrks_oper_month_2021Q4 "Avg no of workers operation per month 2021Q4"

capture label variable item_no "Item no"
capture label variable product_code_3digit "Three digit product code"
capture label variable value_rs "Value (rs)"
capture label variable avg_wrks_full_male "Avg no of workers full time male"
capture label variable avg_wrks_full_female "Avg no of workers full time female"
capture label variable avg_wrks_full_trans "Avg no of workers full time transgender"
capture label variable avg_wrks_part_male "Avg no of workers part time male"
capture label variable avg_wrks_part_female "Avg no of workers part time female"
capture label variable avg_wrks_part_trans "Avg no of workers part time transgender"
capture label variable avg_wrks_total "Avg no of workers total"

capture label variable market_value_owned "Market value of owned assets"
capture label variable market_value_hired "Market value of hired assets"
capture label variable net_additions_assets "Net addition to owned assets"
capture label variable rent_payable_assets "Rent payable for hired assets"

capture label variable org_value_plant_and_mach "Org value of plant & machinery"
capture label variable org_value_equip "Org value of equipment"

capture label variable amount_outstanding "Amount outstanding"
capture label variable interest_payable "Interest payable"

capture label variable amount_rs "Amount (rs)"
capture label variable closing_rs "Closing (rs)"

capture label variable web_presence "Web Presence"
capture label variable intranet_presence "Intranet Presence"
capture label variable inter_sales_orders "Internet Sales Orders"
capture label variable inter_purchase_orders "Internet Purchase Orders"
capture label variable inter_narrowband "Internet Narrowband"
capture label variable inter_fixed_broadband "Internet Fixed Broadband"
capture label variable inter_mobile_broadband "Internet Mobile Broadband"
capture label variable lan_presence "LAN Presence"
capture label variable extranet_presence "Extranet Presence"
capture label variable inter_email "Internet Email"
capture label variable inter_voip "Internet VoIP"
capture label variable inter_goods_services "Internet Goods & Services"
capture label variable inter_govt_info "Internet Govt Information"
capture label variable inter_govt_interaction "Internet Govt Interaction"
capture label variable inter_banking "Internet Banking"
capture label variable inter_financial_services "Internet Financial Services"
capture label variable inter_customer_services "Internet Customer Services"
capture label variable inter_online_delivery "Internet Online Delivery"
capture label variable inter_recruitment "Internet Recruitment"
capture label variable inter_staff_training "Internet Staff Training"
capture label variable monthly_survey_participation "Monthly Survey Participation"
capture label variable email_portal_info_supply "Email Portal Info Supply"
capture label variable avg_employees_computers "Avg Employees Using Computers"
capture label variable avg_employees_inter "Avg Employees Using Internet"

